[package]
name = "lupdate"
version = "0.1.0"
edition = "2021"

[dependencies]
argh = "0.1.7"
assembly-pack = "0.5"
color-eyre = "0.5.11"
env_logger = "0.9"
globset = "0.4.8"
indicatif = "0.16"
log = "0.4"
serde = "1.0"
toml = "0.5.8"
